"""Initial

Revision ID: 3649bb636e7f
Revises: 
Create Date: 2026-02-22 18:55:04.767083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3649bb636e7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cliente_id', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_table('plantas_categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sinonimos', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantas_configuracoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loja_id', sa.String(length=100), nullable=False),
    sa.Column('mapeamento_tipos', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantas_configuracoes_loja_id'), 'plantas_configuracoes', ['loja_id'], unique=True)
    op.create_table('processamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('PLANTAS', 'ANALISE_FOTOS', name='tipoprocessamento'), nullable=False),
    sa.Column('loja_id', sa.String(length=100), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('imagem_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSANDO', 'CONCLUIDO', 'ERRO', name='statusprocessamento'), nullable=True),
    sa.Column('resultado', sa.JSON(), nullable=True),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('tempo_processamento_ms', sa.Integer(), nullable=True),
    sa.Column('meta_dados', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processamentos_created_at'), 'processamentos', ['created_at'], unique=False)
    op.create_index(op.f('ix_processamentos_loja_id'), 'processamentos', ['loja_id'], unique=False)
    op.create_index(op.f('ix_processamentos_status'), 'processamentos', ['status'], unique=False)
    op.create_index(op.f('ix_processamentos_tipo'), 'processamentos', ['tipo'], unique=False)
    op.create_table('analise_fotos_resultados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processamento_id', sa.UUID(), nullable=False),
    sa.Column('tipo_analise', sa.String(length=50), nullable=False),
    sa.Column('resultado', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['processamento_id'], ['processamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantas_enderecos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processamento_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipo_endereco_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('x_pct', sa.Float(), nullable=False),
    sa.Column('y_pct', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('alertas', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['processamento_id'], ['processamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plantas_enderecos')
    op.drop_table('analise_fotos_resultados')
    op.drop_index(op.f('ix_processamentos_tipo'), table_name='processamentos')
    op.drop_index(op.f('ix_processamentos_status'), table_name='processamentos')
    op.drop_index(op.f('ix_processamentos_loja_id'), table_name='processamentos')
    op.drop_index(op.f('ix_processamentos_created_at'), table_name='processamentos')
    op.drop_table('processamentos')
    op.drop_index(op.f('ix_plantas_configuracoes_loja_id'), table_name='plantas_configuracoes')
    op.drop_table('plantas_configuracoes')
    op.drop_table('plantas_categorias')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
